config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :static_pages, only: [] do
    collection do
      post :contact, as: "contact"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contact
    ContactMailer.contact_email(params[:email],
                             params[:subject],
                             params[:message]).deliver
    flash[:success] = "Thanks for sending me an email. I'll get back to you soon!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hey There!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render "shared/header" %>
  <%= yield %>
  <%= render "shared/flash" %>
</body>
</html>

app/views/shared/_flash.html.erb
<script type="text/javascript">
  <% flash.each do |type, message| %>
    toastr.<%= type %>('<%= message %>')
  <% end %>
</script>

app/views/shared/_header.html.erb
<div id="navbar-container" onmouseover="navReveal()" onmouseout="navHide()">
  <div class="hide-medium" id="navbar">
    <%= link_to "Projects", "#", class:"navbar-tab navbar-highlight" %>
    <%= link_to "Home", root_path, class: "navbar-tab" %>
  </div>
</div>
<div class="show-medium" id="navbar-show" onclick="navRevealMobile()"></div>
<div class="show-medium" id="navbar-outside" onclick="navHideMobile()"></div>
<div class="show-medium" id="navbar-menu">
  <%= link_to "Home", root_path, id: 'navbar-home' %>
  <%= link_to "Projects", "#", class:"navbar-tab navbar-highlight" %>
</div>

app/views/shared/_modal.html.erb
<div id="modal-container">
  <div id="modal-content-container">
    <h1 id="modal-contact-headline">Contact Me!</h1>
    <div id="modal-form-container">
      <%= form_tag contact_static_pages_path, method: "post" do %>
        <div id="modal-info-container">
          <%= text_field_tag "email", nil, placeholder: "Email", type: "email", required: "required", id: "modal-email" %>
          <%= text_field_tag "subject", nil, placeholder: "Subject", required: "required", id: "modal-subject" %>
        </div>
        <%= text_area_tag "message", nil, placeholder: "Message", required: "required", id:"contact-text-area" %>
        <%= submit_tag "Submit", class: "inverted-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div id="head-container">
  <div id="index-image">
    <div id="index-black">
      <div id="index-head-content">
        <h1 id="index-headline">Hi, I'm Charles!</h1>
        <div id="index-link-container">
          <%= link_to "Resume", "https://www.dropbox.com/s/qrrielnhu0kwkfl/resume3.pdf?dl=0", class: "button", id: "resume-link", target: "_blank" %>
          <%= link_to "Contact Me!", "#contact", class: "button", id: "contact-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="main-wrapper">
  <div id="main-content-container">
    <div id="about-section-container">
      <h2 class="headline" id="black-headline">
        Constantly
          <span id="learning-headline">learning</span>
        and
          <span id="building-headline"> building</span>.
      </h2>
      <p id="about-content" class="small-container">
        Hey there! I’m currently a second year at <span id="ucb-span" class="about-span">UC Berkeley</span> studying <span id="eecs-span" class="about-span">Computer Science and Electrical Engineering.</span> I love simple code and beautiful design. I also enjoy racket sports, board game nights, jamming out on the guitar, and playing video games. Right now I’m primarily a <span id="rails-span" class="about-span">Rails programmer</span> dabbling in mobile applications, especially <span id="android-span" class="about-span">Android</span>. I’m currently a developer for <span id="bp-span" class="about-span">Cal Blueprint</span>, as well as a staff member of the <span id="coe-span" class="about-span">Berkeley College of Engineering</span>.
      </p>
    </div>
    <div class="section" id="project-section-container">
      <h2 class="headline">
        Stuff I'm doing
      </h2>
      <div id="project-section-project-container">
        <div class="project-container">

        </div>
        <div class="project-container">

        </div>
        <div class="project-container">

        </div>
      </div>
    </div>
    <div class="section" id="contact-section-container">
      <h2 class="headline">
        Want to chat? Message me!
      </h2>
    </div>
  </div>
</div>

<%= render "shared/modal" %>